on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

env:
  HOST: australia-southeast1-docker.pkg.dev
  REPO: connect-staging-365310/connect

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: staging
    env:
      image_url: australia-southeast1-docker.pkg.dev/connect-staging-365310/connect/${{ inputs.app }}
    outputs:
      msgid: ${{ steps.slack.outputs.ts }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
      - name: Create build tag
        id: tag
        run: |
          echo "tag=sha-$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
      - id: slack
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 #v1.23.0
        with:
          channel-id: "C02EE9GUT2S" #deploy
          payload: |
            {
              "text": "Staging ${{ inputs.app }}...",
              "attachments": [
                {
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Ref",
                      "short": true,
                      "value": "${{ github.ref }}"
                    },
                    {
                      "title": "Commit",
                      "short": true,
                      "value": "${{ steps.tag.outputs.sha }}"
                    },
                    {
                      "title": "Message",
                      "short": false,
                      "value": "${{ github.event.head_commit.message }}"
                    },
                    {
                      "title": "View on GitHub",
                      "short": false,
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 #v2.2.1
      - name: Login to Google Container Registry
        run: |
          echo "${{ secrets.GCLOUD_SERVICE_KEY }}" | base64 -d | docker login -u _json_key --password-stdin https://${{ env.HOST }}/
      # unfortunately we can't use deploy keys because the git config dance done by webfactory/ssh-agent happens in the runner
      # not in the docker container. Instead we use an SSH key on 'gpsengine-node' user and forward the access through to the
      # docker container with ssh-agent.
      - name: Install SSH Client
        uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 #v0.7.0 (was v0.5.4)
        with:
            ssh-private-key: ${{ secrets.LIB_CLONE_KEY }}
      - name: Docker build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 #v3.2.0
        with:
          context: .
          push: true
          tags: ${{ env.image_url }}:${{ steps.tag.outputs.tag }},${{ env.image_url }}:latest
          cache-from: type=registry,ref=${{ env.image_url }}:latest
          cache-to: type=inline
          ssh: default=${{ env.SSH_AUTH_SOCK }}
      - if: failure() || cancelled()
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 #v1.23.0
        with:
          channel-id: "C02EE9GUT2S" #deploy
          payload: |
            {
              "text": "Staging ${{ inputs.app }} ${{ job.status }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  update-staging:
    runs-on: ubuntu-latest
    environment: staging
    if: contains(github.ref, 'heads')
    needs:
      - build-and-push
    env:
      image_url: australia-southeast1-docker.pkg.dev/connect-staging-365310/connect/${{ inputs.app }}
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 #v0.7.0 (was v0.5.4)
        with:
          ssh-private-key: ${{ secrets.STAGING_EDIT_KEY }}
      - uses: imranismail/setup-kustomize@6691bdeb1b0a3286fb7f70fd1423c10e81e5375f #v2.0.0 (was v1)
      - run: git clone git@github.com:gpsengine/ConnectStaging.git .
      - run: kustomize edit set image ${{ inputs.app }}=${{ env.image_url }}:sha-$(git rev-parse --short $GITHUB_SHA)
        working-directory: ./app
      - run: git add .
      - run: |
          git config user.email "buildbot@gpsengine.github.com"
          git config user.name "$GITHUB_ACTOR"
      - run: git commit -m "Update ${{ inputs.app }}"
      - run: git push
      - name: Update deployment message on slack
        if: always()
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 #v1.23.0
        with:
          channel-id: "C02EE9GUT2S" #deploy
          #update-ts: ${{ needs.build-and-push.outputs.msgid }}
          payload: |
            {
              "text": "Staged ${{ inputs.app }}",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "${{ job.status == 'success' && '28a745' || 'a72845' }}",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "${{ job.status }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

